### ISSUE TITLE
Predict multiple faces in image

### ISSUE THREAD

**Issue by truongnmt** [ipazc/mtcnn#10]
When run predict on an image, for example:

```python
>>> from mtcnn.mtcnn import MTCNN
>>> import cv2
>>>
>>> img = cv2.imread("ivan.jpg")
>>> detector = MTCNN()
>>> print(detector.detect_faces(img))
```
Is it possible to predict multiple faces in image? Return each face in array element, something like :
```python
[
    {'box': [277, 90, 48, 63], ...},
    {'box': [277, 90, 48, 63], ...},
    {'box': [277, 90, 48, 63], ...}
]
```

**Comment by ipazc** [comment]
Hello @truongnmt , that is already the current behaviour of the package.
Regards,
Iván.

**Comment by truongnmt** [comment]
Awesome! Do you mind update docs? Thanks!
