### ISSUE TITLE
Getting negative image coordinates from 'box' key

### ISSUE THREAD

**Issue by prnvjb** [ipazc/mtcnn#11]
Hi,
Thanks for this amazing MTCNN for faces.
I would like to know why negative coordinates in 'box' key (like (55, -5, 49, 79)) are fetching in face detection.In OpenCV 2d image coordinates starts from (0,0). How to assume this negative coordinates.

**Comment by ipazc** [comment]
Hi @prnvjb ,
thank you for reporting this. It is a bug. You can assume a negative coordinate means 0; it may also happen that the width and height of the box (starting from the top-left coordinates) exceed the width and height of the image.

**Comment by prnvjb** [comment]
ok.
thanks!!

**Comment by isgursoy** [comment]
This can be needed as well:

`        for(int i = 0; i < faces.size(); ++i)
        {
            if(faces[i].bbox.x2 > img.cols)
            {
                faces[i].bbox.x2 = img.cols;
            }

            if(faces[i].bbox.y2 > img.rows)
            {
                faces[i].bbox.y2 = img.rows;
            }
        }`

**Comment by MattyB95** [comment]
@isgursoy Have you got an example of an image which requires this that you can share because I am currently struggling to find a case that requires this?

**Comment by pasqLisena** [comment]
When are you going to release this fix on pip?

**Comment by AliaHamwi** [comment]
hi 
this image give me negative

![John Simm_1](https://user-images.githubusercontent.com/58812068/112283215-951fca80-8c90-11eb-8dcd-0690c25983f2.jpg)

**Comment by MattyB95** [comment]
@AliaHamwi This looks like the same point @pasqLisena made about this fix not being applied to the pip release. Any updates regarding the pip release @ipazc? 

I have tested your image on both versions, and it appears to work under the latest version of this repository:
pip:
`[{'box': [20, -8, 118, 147], 'confidence': 0.9998639822006226, 'keypoints': {'left_eye': (48, 45), 'right_eye': (102, 46), 'nose': (70, 81), 'mouth_left': (49, 97), 'mouth_right': (103, 97)}}]`

Latest (this repository):
`[{'box': [20, 0, 118, 139], 'confidence': 0.9998639822006226, 'keypoints': {'left_eye': (48, 45), 'right_eye': (102, 46), 'nose': (70, 81), 'mouth_left': (49, 97), 'mouth_right': (103, 97)}}]`
![AliaHamwi_drawn](https://user-images.githubusercontent.com/5563995/112482746-49dce900-8d70-11eb-8357-275803418db1.jpg)
