### ISSUE TITLE
Performance is not what it could be

### ISSUE THREAD

**Issue by jxanders** [ipazc/mtcnn#110]
I was testing this repo and then I tested [another repo](https://github.com/blaueck/tf-mtcnn) which implements MTCNN in TF2.

I was able to get ~30ish FPS using the linked repo on CPU. Using this repo I can only get 3 FPS with the same images at the same size using the same MTCNN parameters. I am no ML expert, but I believe this is due to how much numpy is used in this repo vs in the other repo which takes advantage of TF's CPU parallelization.

It might be worth looking into the other repo (also MIT) and using their TF model instead of the numpy weights

**Comment by do335** [comment]
having the same problem
