### ISSUE TITLE
result is not same as facenet?

### ISSUE THREAD

**Issue by lingchingteng** [ipazc/mtcnn#13]
Hi

I use this image as input 

![2007_007763](https://user-images.githubusercontent.com/683816/41399343-a5bcf5ca-6fec-11e8-8486-687c3f6e1b73.jpg)

The result is 

![2007_007763_drawn](https://user-images.githubusercontent.com/683816/41399368-b3471a72-6fec-11e8-8424-b55f1c9c558a.jpg)

I use mtcnn in facenet with the same image, it can catch all faces

i install mtcnn use
pip3 install mtcnn

**Comment by lingchingteng** [comment]
I discover that the cause is imread

facenet use
from scipy import misc
img = misc.imread(image_path)

when i use cv2 the result is 5 faces, when i use misc.imread the result is 7 faces

**Comment by cfong32** [comment]
I had the same problem.
Finally, I found that it is likely because cv2.imread returns channels in BGR order, whereas misc.imread returns them in RGB order.  Channels were different from what the model had been trained on.

**Comment by KLH1472** [comment]
I think the code should be:

from mtcnn.mtcnn import MTCNN
import cv2
img = cv2.imread("ivan.jpg")
detector = MTCNN()
print(detector.detect_faces(img[:,:,::-1]))
