### ISSUE TITLE
Cannot import mtcnn!! because of ImportError "most likely due to a circular import"

### ISSUE THREAD

**Issue by ldiunyh** [ipazc/mtcnn#130]
I got this error all the time. I can't use any single function of this library, tried both on Macos Mojave and Windows 10 with both python 3.7 or 3.11. How can I solve this circular import? Thank you!
![Screen Shot 2024-06-05 at 9 39 54 PM](https://github.com/ipazc/mtcnn/assets/59736240/91c44767-2989-48bb-9743-c7c007ddcb74)
![Screen Shot 2024-06-05 at 9 40 52 PM](https://github.com/ipazc/mtcnn/assets/59736240/f97aa8a5-4f44-4320-8f97-10b5b8de8c5a)

(Cannot import mtcnn because of circular import)

**Comment by ldiunyh** [comment]
Please help!!!!!

**Comment by KVig122** [comment]
Hi, your filename is named "mtcnn.py" - this is conflicting with the mtcnn module name. Simply rename your codefile to anything other than "mtcnn.py" will solve the issue.
