### ISSUE TITLE
python3.6.5 tensorflow 1.10.0 need change keep_dims to keepdims

### ISSUE THREAD

**Issue by blackhilloldmonster** [ipazc/mtcnn#17]
`
WARNING:tensorflow:From test.py:18: calling reduce_mean (from tensorflow.python.ops.math_ops) with keep_dims is deprecated and will be removed in a future version.
Instructions for updating:
keep_dims is deprecated, use keepdims instead

`

**Comment by renatocastro33** [comment]
Just code:

warnings.filterwarnings('ignore')

You can change them but it is just a warning. It's not an error, so it still works.
