### ISSUE TITLE
What's your train set and how do you do data preprocess?

### ISSUE THREAD

**Issue by NeoYeah** [ipazc/mtcnn#18]
as title

**Comment by ShukuiZhang** [comment]
I'm also curious about the training set for the model, is it same as claimed in the paper? Did you find out the answer? @NeoYeah Thanks.

**Comment by bobinush** [comment]
Still no answer for this. You'd think something like this would be written on the Readme 🤷‍♂️

**Comment by KerenElience** [comment]
Sorry, I'm late. The train data used [LFW](http://mmlab.ie.cuhk.edu.hk/archive/CNN/data/train.zip)😂
