### ISSUE TITLE
Is alignment included?

### ISSUE THREAD

**Issue by tengerye** [ipazc/mtcnn#26]
Hi, does the repository include alignment?

**Comment by hbellafkir** [comment]
Nope

**Comment by vandana-rajan** [comment]
@hbellafkir @tengerye 
Sorry. I don't understand. The code provides locations of eyes, nose, mouth etc right? Doesn't alignment mean those landmark localisation? Could you please explain what exactly is missing here?

**Comment by hbellafkir** [comment]
@vandana-rajan 
I thought alignment should include rotating the face too. but you right, alignment here means just returning the landmark points.
