### ISSUE TITLE
How to skip this error? bounding_box = result[0]['box'] IndexError: list index out of range

### ISSUE THREAD

**Issue by arnavw96** [ipazc/mtcnn#29]
I'm trying to process a live video feed and detect faces in every frame, but as soon as I take my face out of the camera's view, I receive an error and the code stops.

Here is a code snippet:

```
cap = cv2.VideoCapture(0)
while(True):
    ret, frame = cap.read()
    detector = MTCNN()
    result = detector.detect_faces(frame)

```
and so on...

This is the error message that I receive when the frame I'm trying to process doesn't have a face.
**bounding_box = result[0]['box']
IndexError: list index out of range**

I wish to skip those frames where there are no faces, and continue the processing (face detection) for further frames.
But the code just stops as soon as it encounters a frame where it cannot detect a face.
Any way to go around this issue? That is - any way to just ignore those frames where no faces are detected, and skip to the next frame?

I'll appreciate soeme help!

**Comment by ipazc** [comment]
First, you should use a single instance of the MTCNN:
```python
cap = cv2.VideoCapture(0)
detector = MTCNN()

while(True):
    ret, frame = cap.read()
    result = detector.detect_faces(frame)
```

second, the result of `detector.detect_faces(frame)` is a list. If there are no faces, the list would have 0 length.

**Comment by arnavw96** [comment]
> First, you should use a single instance of the MTCNN:
> 
> ```python
> cap = cv2.VideoCapture(0)
> detector = MTCNN()
> 
> while(True):
>     ret, frame = cap.read()
>     result = detector.detect_faces(frame)
> ```
> 
> second, the result of `detector.detect_faces(frame)` is a list. If there are no faces, the list would have 0 length.

Thanks! Now I understand the complete function!
This solved the issue:

cap = cv2.VideoCapture(0)
detector = MTCNN()

while(True):
    ret, frame = cap.read()
    result = detector.detect_faces(frame)
    if result: 
          # further processing
