### ISSUE TITLE
changing threshold

### ISSUE THREAD

**Issue by KoteshwarSurga** [ipazc/mtcnn#30]
Hi,
How can we change the threshold of an model for mtcnn.

**Comment by ipazc** [comment]
You can inject the threshold values in the constructor of the MTCNN object. By default the thresholds are these 3 values [0.6, 0.7, 0.7].

```python
    mtcnn = MTCNN(steps_threshold=[0.6, 0.7, 0.7])
```

**Comment by KoteshwarSurga** [comment]
Hi,
Thanks for your reply and actually my doubt is when multiple faces detected
in an same image how we crop the highest confidence score image.

When I used your face detection code I faced the problem is
If 3 faces are detected then it was cropping first one and next cropping
second one but by replacing the first one saving only second image.

So please help me in this problem.

**Comment by ipazc** [comment]
I guess your question is not about the implementation of MTCNN but about how to use the results of MTCNN. Am I right?

**Comment by KoteshwarSurga** [comment]
No I am understand the mtcnn but I am confused in getting cropped results
for image with three persons and I am new to python and much perfect in
python.

So I am confused in cropping the images with highest confidence score

**Comment by ipazc** [comment]
I'm sorry, issues page is not intended to solve such questions/problems outside of MTCNN domain. You might better try asking on stackoverflow.

**Comment by KoteshwarSurga** [comment]
Ok thanks
