### ISSUE TITLE
Not working for Tensorflow 1.8 on my Mac

### ISSUE THREAD

**Issue by Debangsha1992** [ipazc/mtcnn#31]
Hello,

I was running the mtcnn on my mac. It was showing a error at this line:
detector = MTCNN()
AttributeError: module 'tensorflow' has no attribute **ConfigProto**

But when I downgraded my tensorflow from 1.8 to 1.4 it ran.

Also it is not working with tensorflow-gpu. It was giving an Importerror. I had to uninstall it.

Can you please look into the issue ?

Thanks in advance.

**Comment by yeyupiaoling** [comment]
This implementation requires OpenCV>=4.1 and Tensorflow>=1.12.1 installed in the system, with bindings for Python3.They can be installed through pip (if pip version >= 9.0.1):
