### ISSUE TITLE
When i use tensorflow-gpu i got error

### ISSUE THREAD

**Issue by Mi-zo-re** [ipazc/mtcnn#38]
My opencv version is 4-1 and tensorflow-gpu version is 1-13-1, and when i run`detector = MTCNN()` just like what the README said i got a attribute error said ' 'MTCNN' object has no attribute '_MTCNN__session' '. Could anyone tell me how to fix it?

**Comment by Mi-zo-re** [comment]
BTW, when i use tensorflow cpu version everything goes right.

**Comment by jotoy** [comment]
i got the same issue

**Comment by thekhieu** [comment]
i use tensorflow-gpu 1.11.0 and no error
maybe you try to downgrade version

**Comment by hegc** [comment]
AttributeError: module 'tensorflow.compat' has no attribute 'v1'

**Comment by hegc** [comment]
If use TF-gpu v1.*, we should fix the code to compat tf(v1), 
tf.compat.v1.x -> tf.x
tf.nn.max_pool2d -> tf.nn.max_pool
...
, and then the project will work well

**Comment by punitha-valli** [comment]
@ipazc @hegc @jotoy @Mi-zo-re @akofman 

HI,

Hope you are well

As per your suggestion, I am using MTCNN for face detection, I take GPU,

Can you please, tell me how can I able to remove the MTCNN from GPU after it detected the face?

So, if MTCNN was removed from GPU after it detected the face, I can pass CDCN to GPU

image

It is set a different Steps_threshold, at MTCNN it gives different Boundary Box values
The Default Steps_threshold =[0.6,0.7,0.7]

image

Hope for a reply

Thank you

**Comment by hegc** [comment]
You can use retinaface for face detection, which is better than mtcnn. @punitha-valli

**Comment by punitha-valli** [comment]
Hi,

Thank you so much for your reply

Can you please share any github pages for retinaface , mxnet

In my research, I want to detected the face and send to my model to detect
is it spoof or real

So face detected is the initial part to get the faces in the image

Hope for a reply, it will be a great help for my research study

Thanks in advance

**Comment by hegc** [comment]
@punitha-valli 
pytorch: https://github.com/biubug6/Pytorch_Retinaface
mxnet: https://github.com/deepinsight/insightface/tree/master/detection
