### ISSUE TITLE
Tensorflow now supports python 3.7 but mtcnn don't.

### ISSUE THREAD

**Issue by reliefs** [ipazc/mtcnn#47]
Getting this error:
site-packages/mtcnn/mtcnn.py", line 616, in __del__
    self.__session.close()
AttributeError: 'MTCNN' object has no attribute '_MTCNN__session'

Tensorflow now support python 3.7.
https://github.com/tensorflow/tensorflow/issues/31431

**Comment by reliefs** [comment]
fixed it maybe i will update later.

**Comment by reliefs** [comment]
it can be found here for tensorflow 2.0
https://github.com/instabotai/instabotai-webgui

**Comment by reliefs** [comment]
https://github.com/tensorflow/tensorflow/issues/31939

**Comment by punitha-valli** [comment]
@steffanjensen @akofman @knrz @xolott @MattyB95 

HI,

Hope you are well

As per your suggestion, I am using MTCNN for face detection, I take GPU,

Can you please, tell me how can I able to remove the MTCNN from GPU after it detected the face?

So, if MTCNN was removed from GPU after it detected the face, I can pass CDCN to GPU

![image](https://user-images.githubusercontent.com/52031723/112790153-4a87bf00-9091-11eb-9f2e-9df3b011ce43.png)


It is set a different Steps_threshold, at MTCNN it gives different Boundary Box values
The Default Steps_threshold =[0.6,0.7,0.7]

![image](https://user-images.githubusercontent.com/52031723/112790160-4fe50980-9091-11eb-971c-0dbccdc91354.png)


Hope for a reply

Thank you

**Comment by ravan786** [comment]
In my case changing mtcnn version from 0.0.9 to 0.1.0 did the trick
