### ISSUE TITLE
Regarding the MIT License

### ISSUE THREAD

**Issue by ssrp** [ipazc/mtcnn#53]
Hi, thank you for this MTCNN implementation!

Regarding the MIT license of this repo -- if you have used FDDB/WIDERFace dataset for training your models (which are provided only for the research purposes, not commercial usage), how can the weights you provide be on the MIT license?

MIT license allows anyone to use this commercially, which is a derivative work of the images which are not allowed to be used commercially.

Looking forward to your reply. Thanks!

**Comment by ipazc** [comment]
Hi, only the code is released under MIT. You are absolutely right, the weights of the network should not be used for commercial purposes, the model should be retrained in such case, that is why MTCNN accepts weights in the constructor.

I will add clarification upon this. Thank you for this comment.

**Comment by ipazc** [comment]
By the way, the model is an adapted version coming from the original https://github.com/kpzhang93/MTCNN_face_detection_alignment version, which is also released under MIT license. You might be interested in sending also this question to that repo.

**Comment by ssrp** [comment]
Thank you for the fast response and the clarification!
I have raised the same issue on the original repository, thanks!

Also, if you could clear one more thing -- what did you mean when you say "this is why" MTCNN accepts weights in the constructor, is this the usual practice? 
Most of the repositories have released the pre-trained models under MIT License and as the MIT License is non-revocable, it allows companies to use the models. 
Thanks again!

**Comment by ipazc** [comment]
I don't know if it is the usual practice. I understand it is a good way to support custom or different models with the same architecture without the need to override files. That allows having two instances of the MTCNN with different weights at the same time, without modification of the code.

**Comment by RamvigneshPasupathy** [comment]
@ssrp I can see from [here](https://www.tugraz.at/institute/icg/research/team-bischof/lrs/downloads/aflw/) that AFLW Dataset is not meant for commercial use..

> **License Agreement**
>
> The AFLW database is available for non-commercial research purposes only.

But I cannot find any explicit mentions about licensing of [FDDB](http://vis-www.cs.umass.edu/fddb/) or [WIDERFace](http://shuoyang1213.me/WIDERFACE/index.html).

Will be highly helpful if you could share any particular links to articles / documents that claim about the licensing of these datasets.

Thank you.

**Comment by perets-dev** [comment]
ssrp

> 

Hi! Where can i view, that FDDB/WIDERFace dataset can be used only for research purposes, not commercial ones? I can not find the license
