### ISSUE TITLE
Migrate to TF 2.0

### ISSUE THREAD

**Issue by sr1jan** [ipazc/mtcnn#56]
Is there any plan to migrate the codebase to TF 2.0?

Can I contribute to the migration? @ipazc

**Comment by ipazc** [comment]
Of course, pull requests are welcome!

**Comment by fisakhan** [comment]
It is still using APIs from older version of TF in the form of "tf.compat.v1". I also want to contribute to elimination of "tf.compat.v1" and purely use TF 2.0 APIs.

**Comment by reliefs** [comment]
This is working for version 2.0
https://github.com/instabotai/instabotai/tree/master/mtcnn

I made this 2 months ago so it's not 100% up to date with current build but it works.
