### ISSUE TITLE
'MTCNN' object has no attribute '_MTCNN__session'

### ISSUE THREAD

**Issue by Ho-Van-Con** [ipazc/mtcnn#58]
Hi all,
I begin with my project about Face detection using MTCNN, I have issue in line:
>>detector = MTCNN()
Terminal showed as image below
![image](https://user-images.githubusercontent.com/47619692/66739045-1408b500-ee9a-11e9-8430-b503bb3b6e1b.png)

**Comment by ipazc** [comment]
The real error here is "module 'tensorflow' has no attribute 'ConfigProto'" and it is related with the tensorflow version. What version of TF are you using?

Related issues: #47 #56

**Comment by Ho-Van-Con** [comment]
Thank you @ipazc. I fixed this issue

**Comment by nort2002** [comment]
I have a same problem! My tensorflow's version is 2.0.0 gpu what should i do ?

**Comment by nort2002** [comment]
Thank you @ipazc , i fixed this issue  by  changing to tensorflow version 1.14.0

**Comment by reliefs** [comment]
This is working for version 2.0
https://github.com/instabotai/instabotai/tree/master/mtcnn

I made this 2 months ago so it's not 100% up to date with current build but it works.
