### ISSUE TITLE
Running example.py gives no result

### ISSUE THREAD

**Issue by harshithdwivedi** [ipazc/mtcnn#66]
Hi, I'm trying to use `mtcnn` and upon running `example.py`, the only output I get is  : 

```
Using TensorFlow backend.
```
after this, the execution stops without any further error messages.

I'm running this script on Windows 10 with keras 2.0.0.

**Comment by ipazc** [comment]
I could not reproduce this issue. 
What version of tensorflow do you have installed?

**Comment by harshithdwivedi** [comment]
I'm using TensorFlow version 1.15.0

**Comment by ipazc** [comment]
This issue should be fixed in the release version 1.0.0 #133.
