### ISSUE TITLE
No module named 'mtcnn.mtcnn'

### ISSUE THREAD

**Issue by NaeemKhan333** [ipazc/mtcnn#68]
I have installed mtcnn module using 
```
pip install mtcnn
```
But it still giving me following error
ModuleNotFoundError: No module named 'mtcnn.mtcnn'; 'mtcnn' is not a package

**Comment by ipazc** [comment]
Can you please post what Python version are you using? also information regarding the operating system, and if you are using anaconda or not.

**Comment by NaeemKhan333** [comment]
I am Using
-> Python 3.7.3
-> Linux Operating System
-> Anaconda is installed
I am Using anconda based environment for the project

**Comment by ipazc** [comment]
I could not reproduce this issue in a linux environment from scratch with Anaconda and Python 3.7.
Could it be you installed mtcnn with a different pip version (one outside of your anaconda scope)?

**Comment by MattyB95** [comment]
How are you importing the module? `from mtcnn.mtcnn import MTCNN` is outdated in the latest version and should be `from mtcnn import MTCNN`

**Comment by dhruvshettty** [comment]
> How are you importing the module? `from mtcnn.mtcnn import MTCNN` seems to be outdated in the latest version and should be `from mtcnn import MTCNN`

Hello Matty, both methods of import work. The former import searches for the `MTCNN` class from the `mtcnn.py` file (less code, faster). The latter imports the entire `mtcnn.py` file (more code, less fast).

**Comment by Er0r** [comment]
pip install tensorflow

**Comment by Younghyo** [comment]
it seems they are not mtcnn from pypi but `https://github.com/YYuanAnyVision/mxnet_mtcnn_face_detection`.

**Comment by ladyshen** [comment]
您的邮件已接收！
