### ISSUE TITLE
AttributeError: 'str' object has no attribute 'close'

### ISSUE THREAD

**Issue by krunal704** [ipazc/mtcnn#69]
```
from mtcnn.mtcnn import MTCNN
detector = MTCNN(weights_file="/path/to/mtcnn_weights.npy")
```
I want to provide weights file while instantiating MTCNN object because I want to make an executable of my code using pyisntaller, but above code gives me AttributeError.

```
Traceback (most recent call last):
  File "main.py", line 8, in <module>
    detector = MTCNN(weights_file=MTCNN_PATH)
  File "/usr/local/lib/python3.6/dist-packages/mtcnn/mtcnn.py", line 205, in __init__
    weights_file.close()
AttributeError: 'str' object has no attribute 'close'
```

How do I solve this issue can someone please provide the solution or workaround of it
Thanks in advance...

**Comment by ipazc** [comment]
What version of MTCNN are you using? you might need to upgrade it to the latest:

```bash
pip install --upgrade mtcnn
```

**Comment by krunal704** [comment]
@ipazc Thanks for the support
I was using MTCNN v0.0.9 then upgraded to 0.1.0 which solves the problem
