### ISSUE TITLE
Predicting On Batch

### ISSUE THREAD

**Issue by lishangqiu** [ipazc/mtcnn#71]
It is too slow for even Tesla K80(because I need to detect faces in video). Is there any way to predict on batch.

**Comment by devforfu** [comment]
Yeah, the same question here. I would like to load a batch of images to run the predictions on GPU and get the multiple frames output. Is it on the list to be implemented?

**Comment by dwy6626** [comment]
I think padding images together is a possible workaround

**Comment by chaudharyachint08** [comment]
Padding sounds like a good idea, but for large image not sure if it will fit into memory

**Comment by ladyshen** [comment]
您的邮件已接收！
