### ISSUE TITLE
Box coordinates

### ISSUE THREAD

**Issue by karanjakhar** [ipazc/mtcnn#72]
In doc or Readme, it is mentioned that the output for the box is (x,y, width, height) but actually it is giving output as :
(x1, y1, x2, y2) where (x1, y1) is the top-left coordinate and (x2, y2) is bottom right coordinate.

**Comment by StonePanda** [comment]
@karanjakhar hello, i get the output as (x,y,width,height) which (x,y) is the coordinate of the top-left.

**Comment by punitha-valli** [comment]
@karanjakhar @StonePanda @akofman @knrz @xolott 

How to implement for the customized dataset (my dataset is OULU),

Can you please share your experience,

Thanks in advance
