### ISSUE TITLE
Performance of mtcnn package

### ISSUE THREAD

**Issue by LShostenko** [ipazc/mtcnn#8]
It turns out that the speed of face detection with mtcnn package is almost two times slower than with the original implementation of [facenet](https://github.com/davidsandberg/facenet).

**Comment by ipazc** [comment]
Hello @LShostenko. I could not reproduce this issue. 

For an RGB image with 900x1260 pixels, the process time for both implementations is almost the same:

Facenet - Total time: 0.5284574031829834
mtcnn package - Total time: 0.5193462371826172

Perhaps it might be related to the usage of the GPU. The mtcnn package is currently not allowing configuration for this scenario. Could you please post your benchmark and configuration?

If you need it, I can provide you a simple script for using the MTCNN version from facenet - the one I created for this benchmark.

**Comment by LShostenko** [comment]
Sorry, my mistake. Indeed the performance of both implementation is almost the same. I did my measures with modified code integrated to our company repository.
