### ISSUE TITLE
Incompatible with tensorflow 2.0

### ISSUE THREAD

**Issue by blahBlahhh** [ipazc/mtcnn#83]
Looks like the TensorFlow backend used in this Keras model is still on tf 1.0, so when I try`mtcnn = MTCNN()`, I get an error of `AttributeError: module 'tensorflow' has no attribute 'get_default_graph'`
Can you please implement a version compatible with tf2.0?

**Comment by blahBlahhh** [comment]
Well, I got into factory.py and import tensorflow.keras instead, and it solved the problem.
But please update anyways.

**Comment by christian-rncl** [comment]
#85
