### ISSUE TITLE
Passing batch of images for faster processing

### ISSUE THREAD

**Issue by Neltherion** [ipazc/mtcnn#9]
Hi, First of all thanks so much for your effort in bringing MTCNN to Python in an easy usable way.

I wanted to know if there is a way to pass a batch of images (instead of just one image) to the GPU to increase the overall speed of face detections for lots of images.

Thanks again

**Comment by ipazc** [comment]
Hello @Neltherion . Right now there isn't a way to process a batch of images, but I'll work on it.
Thank you for the suggestion!

**Comment by Neltherion** [comment]
@ipazc Thanks. I'll be watching your progress...

**Comment by YaroslavSchubert** [comment]
@Vermeille  something like 40-60ms on 1920x1080

**Comment by SuperBo** [comment]
I also want this features, when will batch input will be available?

**Comment by hbellafkir** [comment]
@ipazc are you still woking on it, or its a dead thing ?

**Comment by chaudharyachint08** [comment]
> @Vermeille something like 40-60ms on 1920x1080

I tried on GPU instance on Google-colab. For 1280x720 image it took around a second, not at all fast as I was expecting initially

**Comment by Vinayrraj** [comment]
> Hello @Neltherion . Right now there isn't a way to process a batch of images, but I'll work on it.
> Thank you for the suggestion!

Hi @ipazc, if possible will you be able to suggest by when we can expect this feature?

**Comment by chaudharyachint08** [comment]
@ipazc  Still waiting for Batch level implementation, see if you can help
