### ISSUE TITLE
('Tensor Tensor("conv2d_21/BiasAdd:0", shape=(?, ?, ?, 4), dtype=float32) is not an element of this graph.',)

### ISSUE THREAD

**Issue by little7Li** [ipazc/mtcnn#91]
Hi, when i use `faces = mtcnn_detector.detect_faces(image)` in a web server, i got this error. 
any idea?

**Comment by legraphista** [comment]
Hi @little7Li, have you loaded MTCNN on another thread than the one you're trying to use it?

I recently had this problem, looks like tensorflow doesn't like using graphs across threads, see https://github.com/tensorflow/tensorflow/issues/14356#issuecomment-385962623
