### ISSUE TITLE
negative value in face box ?

### ISSUE THREAD

**Issue by shelldonhu** [ipazc/mtcnn#92]
`x, y, width, height = face['box']`
I test a picture, but got y equals -25

### code:
```python
from mtcnn import MTCNN
import cv2

img = cv2.cvtColor(cv2.imread("6.jpg"), cv2.COLOR_BGR2RGB)
detector = MTCNN()
res = detector.detect_faces(img)
print(res)
```

### output:
```bash
Using TensorFlow backend.
2020-06-06 13:25:22.146922: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa34b334670 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-06-06 13:25:22.146983: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
[{'box': [43, -25, 177, 262], 'confidence': 0.990744948387146, 'keypoints': {'left_eye': (122, 89), 'right_eye': (191, 81), 'nose': (178, 133), 'mouth_left': (121, 174), 'mouth_right': (184, 168)}}]
```

### picture(6.jpg):
![6](https://user-images.githubusercontent.com/16998373/83936842-ec37da00-a7f9-11ea-92e6-e9c144c08bca.jpg)

**Comment by pjshwa** [comment]
Try applying this pull request. https://github.com/ipazc/mtcnn/pull/70

**Comment by shelldonhu** [comment]
@pjshwa 

Thank you! My solution is to modify on my code, similar to your pull request. But your pull request does not adjust box's width and height, the author said that:

>  it may also happen that the width and height of the box (starting from the top-left coordinates) exceed the width and height of the image.

![image](https://user-images.githubusercontent.com/16998373/83946350-b9660400-a842-11ea-92ed-d2d62cbe8ce5.png)

**Comment by shelldonhu** [comment]
Thank you! @MattyB95 @ipazc @pjshwa
